gitlab:
  url: "https://gitlab.com/api/v4"  # GitLab API base URL
  token: "<YOUR_ACCESS_TOKEN>"       # GitLab personal access token
  group_id: "<YOUR_GROUP_ID>"        # Main GitLab group ID
  subgroup_id: ""                     # optional
  milestone_keywords:                # Milestone names to search for
    - ["Prototípus I", "Prototípus 1", "Prototype I", "Prototype 1", "Mérföldkő II", "Mérföldkő 2"]
    - ["Prototípus II", "Prototípus 2", "Prototype II", "Prototype 2", "Mérföldkő III", "Mérföldkő 3"]
    - ["Kész termék", "Végleges termék", "Finished", "Mérföldkő IV", "Mérföldkő 4"]

project:
  clone_dir: "./repos"              # Directory where repositories will be cloned

analyzer:
  solution_dir: "../CodeMetricsAnalyzer"  # Base directory of your .NET solution
  project_dir: "../CodeMetricsAnalyzer/CodeMetricsAnalyzer/"  # Directory of the executable project
  project_file: "CodeMetricsAnalyzer.csproj"  # The main project file to run
  unity_path: "" # optional, the Unity.exe path for creating .sln files for Unity projects